Repository LindaHlubi/Project-1, pull requests merged in 2021-01, with the labels that each got.

#19 quick search calls api and returns recipes to centre div
  index.html
  scripts/scripts.js
Labels: enhancement

#25 commit readme
  README.md
Labels: documentation

#26 added validation and initial load of storeKeyword
  scripts/keyword-search.js
Labels: bug

#27 Modal ins ing
  scripts/random_recipe.js
  scripts/scripts.js
Labels: enhancement

#30 Split email & modal JS files
  index.html
  scripts/email.js
  scripts/modal.js
  scripts/scripts.js
Labels: enhancement

#32 Ad to favourites
  index.html
  scripts/addFavourite.js
Labels: enhancement

#41 Adding links to favs
  index.html
  scripts/addFavourite.js
  scripts/mainPage.js
  scripts/random_recipe.js
  scripts/scripts.js
Labels: enhancement

#42 Expand favourites
  index.html
  scripts/addFavourite.js
  scripts/favouriteAdd.js
  scripts/favouriteView.js
  scripts/mainPage.js
  scripts/scripts.js
Labels: enhancement

#43 Tidy html
  index.html
  style/style.css
Labels: bug

#53 Ad disposable container
  index.html
  scripts/aboutUs.js
  scripts/favouriteAdd.js
  scripts/mainPage.js
  scripts/scripts.js
Labels: enhancement

#57 Single recipe view
  index.html
  scripts/favouriteAdd.js
  scripts/mainPage.js
  scripts/recipeViewSingle.js
  style/style.css
Labels: enhancement

#60 Move collage to file
  collage.html
  index.html
  scripts/aboutUs.js
  scripts/mainPage.js
Labels: enhancement
